import type { AgentDefinition, UserId } from "@render-harness/core";
import type { Hono } from "hono";

export interface BlueprintRouteContext {
  auth: (req: Request) => Promise<UserId | null>;
  agents: Record<string, AgentDefinition>;
  queue: string;
  pathPrefix: string;
}

export function registerBlueprintRoutes(app: Hono, ctx: BlueprintRouteContext): void {
  const { auth, agents, queue, pathPrefix } = ctx;
  const r = (path: string) => `${pathPrefix}${path}`;

  app.get(r("/blueprint"), async (c) => {
    const userId = await auth(c.req.raw);
    if (!userId) return c.json({ error: "unauthorized" }, 401);
    const yaml = renderBlueprint({ agents, queue });
    return c.body(yaml, 200, { "content-type": "text/yaml; charset=utf-8" });
  });
}

/**
 * Emit a starter `render.yaml` Blueprint for the loaded agent. Mirrors
 * the structure of `blueprints/render.private.yaml` but parameterised
 * by the agent and queue this service is configured with so the user
 * gets a copy-pasteable starting point that matches their local stack.
 *
 * Deliberately conservative: the emitted yaml uses placeholders for
 * destination paths (rootDir, build/start commands) so the user can
 * adapt it to their repo layout. Required env vars are listed but
 * marked `sync: false` — the user fills them in via the Dashboard.
 */
function renderBlueprint(args: { agents: Record<string, AgentDefinition>; queue: string }): string {
  const agentList = Object.values(args.agents);
  const primary = agentList[0];
  const agentName = primary?.name ?? "operator-demo";
  const slug = agentName.toLowerCase().replace(/[^a-z0-9-]/g, "-");

  // Aggregate provider keys from every loaded agent so any model the
  // user might be using shows up in the env list.
  const providerKeys = new Set<string>();
  for (const a of agentList) {
    if (a.model.apiKeyEnv) providerKeys.add(a.model.apiKeyEnv);
    else if (a.model.provider === "anthropic") providerKeys.add("ANTHROPIC_API_KEY");
    else if (a.model.provider === "openai-compat") providerKeys.add("OPENAI_API_KEY");
  }

  const providerEnvLines = [...providerKeys]
    .map((name) => `      - key: ${name}\n        sync: false`)
    .join("\n");

  return `# yaml-language-server: $schema=https://render.com/schema/render.yaml.json
#
# Starter Blueprint generated by /blueprint for the "${agentName}" agent.
# Mirrors the operator-demo local stack: public web service + background
# worker + Postgres + Key Value. Adjust rootDir / buildCommand /
# startCommand to match your repo layout, then deploy.

databases:
  - name: ${slug}-db
    plan: basic-256mb
    region: oregon
    postgresMajorVersion: "17"

services:
  - type: web
    name: ${slug}-web
    runtime: node
    region: oregon
    plan: starter
    rootDir: .
    buildCommand: pnpm install --no-frozen-lockfile && pnpm --filter @render-harness/example-${slug} build
    startCommand: node examples/${slug}/dist/web.js
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: WORKER_QUEUE
        value: ${args.queue}
      - key: DATABASE_URL
        fromDatabase:
          name: ${slug}-db
          property: connectionString
      - key: KV_URL
        fromService:
          name: ${slug}-kv
          type: keyvalue
          property: connectionString
      - key: WEB_API_KEY
        sync: false
      - key: UI_COOKIE_SECRET
        generateValue: true

  - type: worker
    name: ${slug}-worker
    runtime: node
    region: oregon
    plan: starter
    rootDir: .
    buildCommand: pnpm install --no-frozen-lockfile && pnpm --filter @render-harness/example-${slug} build
    startCommand: node examples/${slug}/dist/worker.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: LOG_LEVEL
        value: info
      - key: WORKER_QUEUE
        value: ${args.queue}
      - key: DATABASE_URL
        fromDatabase:
          name: ${slug}-db
          property: connectionString
      - key: KV_URL
        fromService:
          name: ${slug}-kv
          type: keyvalue
          property: connectionString
${providerEnvLines}

  - type: keyvalue
    name: ${slug}-kv
    plan: free
    region: oregon
    ipAllowList: []
`;
}
